### ISSUE TITLE
HttpRequestException: Failed to proxy the request

### ISSUE THREAD

**Issue by mishmish30** [Jaxelr/VueSimpleTemplate#13]
An unhandled exception occurred while processing the request.
HttpRequestException: The server returned an invalid or unrecognized response.

System.Net.Http.HttpConnection.ThrowInvalidHttpResponse()
HttpRequestException: Failed to proxy the request to https://localhost:44321/dist/vendor.js, because the request to the proxy target failed. Check that the proxy target server is running and accepting requests to https://localhost:44321/.

The underlying exception message was 'The server returned an invalid or unrecognized response.'.Check the InnerException for more details.

Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task<Uri> baseUriTask, CancellationToken applicationStoppingToken, bool proxy404s)

i used    spa.UseVueCli(npmScript: "serve", port: 44321); // optional port

**Comment by mishmish30** [comment]
i used this settings project (csproj,Startup) and working fine , please take a look ... thanks ♥

https://github.com/weicheng95/VueDotnetCoreTemplate

**Comment by Jaxelr** [comment]
The port configured on the startup.cs [line 78](https://github.com/Jaxelr/VueSimpleTemplate/blob/master/Content/Startup.cs#L78) allows to serve the vue clientApp on a diff port than the API, you could change that to suit your needs.
