### ISSUE TITLE
Release 0.3.7 is broken

### ISSUE THREAD

**Issue by Jaxelr** [Jaxelr/VueSimpleTemplate#17]
Release 0.3.7 doesnt work on netcore 3.0

- Dotnet version: nercore3.0
- Library version: 0.3.7

**Comment by Jaxelr** [comment]
Fixed on version 0.4.0

**Comment by yobretyo** [comment]
I tried to use this in dotnet... in VS. but after talking to people from VS on twitter, said it’s a bad code
