### ISSUE TITLE
NodeInvocationException: Prerendering failed because of error: Error: Cannot find module '/PATH/Coding/WebDev/ASP.Net/Vue/SimpleVue/ClientApp/build/renderOnServer'

### ISSUE THREAD

**Issue by eddyekofo94** [Jaxelr/VueSimpleTemplate#5]
# SSR error

I just created a new project and this is the error I am getting
## Steps to reproduce
`dotnet new simplevue -o SimpleVue
`
`cd ClientApp && yarn`
`dotnet run`

## The stack

`NodeInvocationException: Prerendering failed because of error: Error: Cannot find module '/PATH/Coding/WebDev/ASP.Net/Vue/SimpleVue/ClientApp/build/renderOnServer' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15) at Function.Module._load (internal/modules/cjs/loader.js:507:25) at Module.require (internal/modules/cjs/loader.js:637:17) at require (internal/modules/cjs/helpers.js:20:18) at findBootModule (/private/var/folders/_x/r4zc198s3yv72x44p28vjjl80000gn/T/vlt4iscp.54z:111:17) at findRenderToStringFunc (/private/var/folders/_x/r4zc198s3yv72x44p28vjjl80000gn/T/vlt4iscp.54z:116:28) at renderToStringImpl (/private/var/folders/_x/r4zc198s3yv72x44p28vjjl80000gn/T/vlt4iscp.54z:75:51) at /private/var/folders/_x/r4zc198s3yv72x44p28vjjl80000gn/T/xeksnuxe.flg:114:19 at IncomingMessage.<anonymous> (/private/var/folders/_x/r4zc198s3yv72x44p28vjjl80000gn/T/xeksnuxe.flg:133:38) at IncomingMessage.emit (events.js:182:13) Current directory is: /Users/eddyekofo/Coding/WebDev/ASP.Net/Vue/SimpleVue
Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.InvokeExportAsync<T>(NodeInvocationInfo invocationInfo, CancellationToken cancellationToken)
Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.InvokeExportAsync<T>(CancellationToken cancellationToken, string moduleName, string exportNameOrNull, object[] args)
Microsoft.AspNetCore.NodeServices.NodeServicesImpl.InvokeExportWithPossibleRetryAsync<T>(string moduleName, string exportedFunctionName, object[] args, bool allowRetry, CancellationToken cancellationToken)
Microsoft.AspNetCore.NodeServices.NodeServicesImpl.InvokeExportWithPossibleRetryAsync<T>(string moduleName, string exportedFunctionName, object[] args, bool allowRetry, CancellationToken cancellationToken)
Microsoft.AspNetCore.SpaServices.Prerendering.PrerenderTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.RunAsync(TagHelperExecutionContext executionContext)
AspNetCore.Views_Main_Index.ExecuteAsync()
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, bool invokeViewStarts)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync<TFilter, TFilterAsync>()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext<TFilter, TFilterAsync>(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

**Comment by Jaxelr** [comment]
Hi, which version of the template are you using?

**Comment by Jaxelr** [comment]
Yes, ill take a look. Thanks.

**Comment by Jaxelr** [comment]
Thanks a lot for reporting this bug, the problem was that i left a dependency on the packed nupkg from version 0.1.*. Im packaging a version 0.2.1 that corrects this bug, expect it today.

**Comment by Jaxelr** [comment]
Closing this issue since i published 0.2.1, if your situation persists while using 0.2.1 feel free to reopen.
