### ISSUE TITLE
.editorconfig is not exist

### ISSUE THREAD

**Issue by Weilence** [Jaxelr/VueSimpleTemplate#8]
# Describe the bug

Solution has .editorconfig file, but file is not exist.

## Steps to reproduce

1. install template
2. new a solution

## Expected behavior

- .editorconfig is exist in root folder

**Comment by Jaxelr** [comment]
Oh yep, this is a bug, expect a fix between today and tomorrow in version 0.2.3

**Comment by Jaxelr** [comment]
Fixed on release 0.2.3.
